proxies:
- name: id-biznet1
  server: updates.netflix.com
  port: 80
  type: trojan
  password: 925d1aa0-b179-11ee-9301-1239d0255272
  skip-cert-verify: true
  udp: true
  network: ws
  sni: sg3.socifiles.com
  ws-opts:
    path: /trojanws
    headers:
       Host: sg3.socifiles.com