#!/bin/bash
#=================================================
# File name: init-settings.sh
# Description: This script will be executed during the first boot
#=================================================
# Set default LAN_IP AND themes
# sed -i 's/192.168.1.1/192.168.5.1/' /etc/config/network
uci batch << EOF
set network.lan.ipaddr='192.168.1.1'
set luci.main.mediaurlbase='/luci-static/argon'
uci del network.lan.force_link
commit
EOF

# Set Timezone to Asia/Jakarta
uci set system.@system[0].hostname='AldevWrt'
uci set system.@system[0].timezone='WIB-7'
uci set system.@system[0].zonename='Asia/Jakarta'
uci set system.@system[0].log_size='1040'
uci set system.@system[0].log_file='/root/system.log'
uci commit

uci del tinyfilemanager.@main[0].auth_users
uci del tinyfilemanager.@main[0].readonly_users
uci set tinyfilemanager.@main[0].use_auth='0'
uci set tinyfilemanager.@main[0].global_readonly='0'
uci set tinyfilemanager.@main[0].max_upload_size='250'
uci commit

uci set ttyd.@ttyd[0].debug='7'
uci set ttyd.@ttyd[0].command='/bin/login -f root'
uci set dhcp.lan.force='1'
uci commit

# Set argon as default theme
uci set argon.@global[0].mode='dark'
uci set argon.@global[0].online_wallpaper='none'
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit

uci set network.m_usb0=interface
uci set network.m_usb0.proto='dhcp'
uci set network.m_usb0.device='usb0'
uci set network.m_usb0.metric='1000'

uci set network.m_usb1=interface
uci set network.m_usb1.proto='dhcp'
uci set network.m_usb1.device='usb1'
uci set network.m_usb1.metric='2000'

uci set network.m_eth1=interface
uci set network.m_eth1.proto='dhcp'
uci set network.m_eth1.device='eth1'
uci set network.m_eth1.metric='3000'

uci set network.m_eth2=interface
uci set network.m_eth2.proto='dhcp'
uci set network.m_eth2.device='eth2'
uci set network.m_eth2.metric='4000'

uci set network.utun=interface
uci set network.utun.proto='none'
uci set network.utun.device='utun'
uci set network.utun.force_link='1'
uci commit network

uci add_list firewall.@zone[0].network='utun'
uci add_list firewall.@zone[1].network='m_usb0'
uci add_list firewall.@zone[1].network='m_usb1'
uci add_list firewall.@zone[1].network='m_eth1'
uci add_list firewall.@zone[1].network='m_eth2'
uci set firewall.@defaults[0].input='ACCEPT'
uci commit firewall

# Disable IPV6 ula prefix
# sed -i 's/^[^#].*option ula/#&/' /etc/config/network

# Set default shell
which zsh && sed -i -- 's:/bin/bash:'`which zsh`':g' /etc/passwd

#chmod +x /bin/kodok_loncat

chmod +x /bin/oc86
oc86
chmod +x files/etc/openclash/core/clash*

opkg remove luci-i18n-base-zh-cn --force-depends

echo "neofetch" > /root/.oh-my-zsh/custom/immortal.zsh

sed -i "s/\/bin\/ash/\/usr\/bin\/zsh/g" /etc/passwd

#sed -i "s/let data = value.fd.read(1024)/let data = value.fd.read(102400)/" /usr/share/ucode/luci/http.uc

sed -i 's#let data = value.fd.read(1024)#let data = value.fd.read(1024000)#g' /usr/share/ucode/luci/http.uc

sed -i 's#"show_hidden":false#"show_hidden":true#g' /www/tinyfilemanager/index.php
#sed -i 's#"theme":"light"#""theme":"dark"#g' /www/tinyfilemanager/index.php

# Add the default password for the 'root' user（Change the empty password to 'password'）
sed -i 's/root:::0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.::0:99999:7:::/g' /etc/shadow

rm -rf /usr/share/luci/menu.d/luci-proto-modemmanager.json

#uci set fstab.@global[0].anon_mount='1'
#uci commit fstab

chmod +x /etc/init.d/cloudflared

#/usr/bin/cloudflared service install eyJhIjoiNmNkNTRkYzVlMmE3MDQ5YWU4

/etc/init.d/cloudflared enable
/etc/init.d/cloudflared start

chmod +x /www/netmon/vnstati.sh
/www/netmon/vnstati.sh

echo '*/5 * * * * /www/netmon/vnstati.sh >/dev/null 2>&1' >> /etc/crontabs/root
/etc/init.d/cron restart

/etc/init.d/samba4 restart



#metacubexd
#tar -xzf /etc/openclash/compressed-dist.tgz -C /usr/share/openclash/ui/dashboard && rm /etc/openclash/compressed-dist.tgz

chmod +x /lib/preinit/80_mount_root

# remove huawei me909s usb-modeswitch
sed -i -e '/12d1:15c1/,+5d' /etc/usb-mode.json
# remove dw5821e usb-modeswitch
sed -i -e '/413c:81d7/,+5d' /etc/usb-mode.json



echo "Setting permission..."
chmod +x /usr/bin/repair_ro  > /dev/null

#echo "Adding to startup..."
if ! grep -q 'repair_ro' /etc/rc.local; then
    sed -i '/exit 0/i repair_ro' /etc/rc.local 2>/dev/null
fi

rm -rf /usr/lib/lua/luci/i18n
rm -rf /etc/uci-defaults/luci-i18n*
#rm -rf /etc/hotplug.d/iface/20-firewall

rm -rf /tmp/luci-modulecache/
rm -rf /tmp/luci-indexcache*

exit 0
