---
rule-providers:
  rl_combolite:
    type: http
    behavior: classical
    path: "./rule_provider/aldev_combolite.yaml"
    url: https://raw.githubusercontent.com/18rudi/rule-openclash/main/aldev_combolite.yaml
    interval: 28800
  rl_netflix:
    type: http
    behavior: classical
    path: "./rule_provider/aldev_netflix.yaml"
    url: https://raw.githubusercontent.com/18rudi/rule-openclash/main/aldev_netflix.yaml
    interval: 28800
  rl_others:
    type: http
    behavior: classical
    path: "./rule_provider/aldev_vpn_others.yaml"
    url: https://raw.githubusercontent.com/18rudi/rule-openclash/main/aldev_vpn_others.yaml
    interval: 28800
#  oisd_big:
#    type: http
#    behavior: classical
#    path: "./rule_provider/oisd_big.yaml"
#    url: https://raw.githubusercontent.com/hillz2/openclash_adblock/main/oisd_big.yaml
#    interval: 28800 # Update rules every 8 hours
proxy-providers:
  PP-vpn:
    type: file
    path: "./proxy_provider/vpn.yaml"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 100
proxy-groups:
- name: lb_eth
  type: load-balance
  strategy: round-robin
  proxies:
  #- e_1
  - u_0
  - u_1
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: at_eth
  type: fallback
  proxies:
  - u_0
  - u_1
  #- e_1
  url: http://www.gstatic.com/generate_204
  interval: 100
- name: at_other
  type: fallback
  proxies:
  - s_vpn
  - u_0
  - u_1
  #- e_1
  url: http://www.gstatic.com/generate_204
  interval: 100
- name: e_1
  type: select
  disable-udp: false
  interface-name: eth1
  proxies:
  - DIRECT
- name: u_0
  type: select
  disable-udp: false
  interface-name: usb0
  proxies:
  - DIRECT
- name: u_1
  type: select
  disable-udp: false
  interface-name: usb1
  proxies:
  - DIRECT
- name: combolite
  type: select
  disable-udp: false
  proxies:
  #- e_1
  - u_0
  - u_1
  - at_eth
  #- s_vpn
  #- lb_eth
- name: netflix
  type: select
  disable-udp: false
  proxies:
 # - e_1
  - u_0
  - u_1
  - at_eth
 # - s_vpn
 # - b_vpn
  url: http://www.gstatic.com/generate_204
  interval: 100
- name: others
  type: select
  disable-udp: false
  proxies:
  - at_other
  - u_0
  - u_1
  - at_eth
  - s_vpn
 # - b_vpn
  url: http://www.gstatic.com/generate_204
  interval: 100
#- name: eth
#  type: select
#  disable-udp: false
#  proxies:
#  - e_1
#  - u_0
#  - u_1
#  - at_eth
  #- s_vpn
#- name: b_vpn
#  type: fallback
#  disable-udp: false
#  use:
#  - PP-vpn
#  url: http://www.gstatic.com/generate_204
#  interval: 100
- name: s_vpn
  type: select
  disable-udp: false
  use:
  - PP-vpn
#- name: TrafficAds
#  type: select
#  proxies:
#  - REJECT
  #- e_1
#  - u_0
#  - u_1
rules:
#- RULE-SET,rl_eth,eth
#- DST-PORT,7895,REJECT
#- DST-PORT,7892,REJECT
#- DOMAIN-SUFFIX,googlesyndication.com,eth
#- GEOSITE,oisd-full,TrafficAds
#- GEOSITE,rule-ads,TrafficAds
#- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
#- IP-CIDR,198.18.0.1/16,REJECT,no-resolvePL
#whatsapp
- DST-PORT,3478/4244/5222/5223/5228/5288/5242/5349/34784/45395/50318/59234/12222/11112/25566,GLOBAL,udp
#- DOMAIN-KEYWORD,whatsapp,eth
#- MLBB
#- DST-PORT,5000-5221/5224-5227/5229-5241/5243-5287/5289-5352/5354-5509/5517/5520-5529/5551-5559/5601-5700/8443/9000-9010/9443/10003/30000-30300,game,tcp
#- DST-PORT,5517-5529/5551-5559/5601-5700/8001/8130/8443/9000-9010/9120/9992/10003/30000-30300,game,udp
#- RULE-SET,rule_personalads,TrafficAds
#- RULE-SET,rule_basicads,TrafficAds
#- RULE-SET,rule_hijacking,TrafficAds
#- RULE-SET,rule_privacy,TrafficAds
#- RULE-SET,adaway,TrafficAds
#- RULE-SET,adguard_dns,TrafficAds
#- RULE-SET,oisd_big,REJECT
- RULE-SET,rl_combolite,combolite
- RULE-SET,rl_netflix,netflix
- RULE-SET,rl_others,others
- MATCH,GLOBAL
unified-delay: true
