name: up_eks2

on:
  workflow_dispatch:
env:
  paket_eksternal: https://op.dllkids.xyz/packages/x86_64

jobs:
  download_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -f "externalpaket.txt" ]; then
            rm externalpaket.txt
            git add -u
            git commit -m "Remove externalpaket.txt" || true
            git push
          fi

      - name: Download Packages Manifest
        run: |
          wget -O abc.txt ${{ env.paket_eksternal }}/Packages.manifest
          grep -o 'Filename: [^ ]*' abc.txt | awk '{print "${{ env.paket_eksternal }}/" $2}' > externalpaket.txt
        shell: bash

      - name: Copy Text if Contained
        run: |
          if [ -f "paket_download.txt" ]; then
            while read -r pattern; do
              grep "$pattern" externalpaket.txt >> copied_text.txt
            done < paket_download.txt
          fi
        shell: bash

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add abc.txt
          git add externalpaket.txt
          git add copied_text.txt
          git commit -m "Add Packages Manifest and Copied Text"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/zero2black/wrtbuild.git main
